### ISSUE TITLE
优秀,就是后台无法自动抢,必须是微信画面.

### ISSUE THREAD

**Issue by Zziwen** [mxruan/WechatLuckyMoney#1]
如果加个后台抢就完美了,还有息屏自动抢红包

**Comment by mxruan** [comment]
> 如果加个后台抢就完美了，还有息屏自动抢红包

是的，这个版本只有在微信首页聊天列表 或 具体聊天页面才可以抢红包。
短时间内没有充分的精力扩展其他功能，不过我会持续跟进这个项目的，谢谢你的关注！

**Comment by gangjin1991** [comment]
为什么我的手机不行，开启插件就直接跳到无障碍设置页，服务已经打开了。换了别的手机就可以。
